export const ON_CHANGE_REGISTER = "ON_CHANGE_REGISTER";
export const ON_CHANGE_LOGIN = "ON_CHANGE_LOGIN";
export const STATUS_API = "STATUS_API";
export const BACK_DEFAULT_CHANGE = "BACK_DEFAULT_CHANGE";
